### ISSUE TITLE
"Align and split" error

### ISSUE THREAD

**Issue by elcortegano** [huangs001/AlignGraph2#2]
I recently installed this tool, and run it as:

    python3 AlignGraph2.py -t 60 -r reads.fq -c assembly.fa -g similar_genome.fa -o /scratch/elopez/poolfounders

But I get the following error:

>Total read=4149430
Read iterator Done
Filter Done
All Done
/scratch/elopez/AlignGraph2/thirdparty/mecat/Linux-amd64/bin/mecat2ref: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
K-Mer counting...
Done
Read to Contig...
Done
Read to Ref...
Done
Contig to Ref...
Done
Pre process...
Done
PAGraph...
Done
Extract and split...
Done
Align and split...
Traceback (most recent call last):
  File "/scratch/elopez/AlignGraph2/./AlignGraph2.py", line 486, in <module>
    cns_helper.split_ref(os.path.join(cns_wrk_mecat_dir, 'merge.ref'), cns_wrk_ref_dir, mapping)
  File "/scratch/elopez/AlignGraph2/script/cns_helper.py", line 43, in split_ref
    with open(ref_path) as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/elopez/AlignGraph2/poolfounders/working_dir/cns/wrk/mecat/merge.ref'

What could be causing the problem? In relation with the error message, `libgomp.so.1` is in my PATH variable.

In case it helps, these are the versions of the dependencies in my system:

- GCC 6.3.0
- CMake 3.25.0
- Python 3.11.0
- Biopython 1.80

**Comment by elcortegano** [comment]
Solved. I run the exact same script on a different node and for some reason there it worked. Looks like a subtle problem, but definitely one on my side.

Have a different issue now, which is that the program seems to be stuck at one step without progress (I also see it using only one thread, even when -t 60 was used). But that's a different issue.
